### ISSUE TITLE
Why we set horovodjob`s sshport default is 33?

### ISSUE THREAD

**Issue by xieydd** [AliyunContainerService/arena#27]
A litter confuse about sshport

```
--sshPort int           ssh port. (default 33)
```

**Comment by cheyang** [comment]
Because it's using hostNetwork by default, and we have to avoid conflict the default host port 22. I suggest you to use mpijob which can cover the horovodjob capabilities and don't use sshport for communication.

**Comment by xieydd** [comment]
If i want to use calico newwork , horovodjob or mpijob? @cheyang

**Comment by cheyang** [comment]
Yeah, MPI job supports other framework.

**Comment by xieydd** [comment]
@cheyang So horovodjob will be discarded in the future? Thanks a lot .

**Comment by cheyang** [comment]
Yeah. It will be deprecated when MPI operator is stable.
