### ISSUE TITLE
SomeThing about horovodjob?

### ISSUE THREAD

**Issue by xieydd** [AliyunContainerService/arena#36]
1. Have you consider offering one horovodjob demo in home page.
2. The init container of mpijob git-sync ,does it provide the same functionality of the init container of horovodjob rsync
@cheyang

**Comment by cheyang** [comment]
> 1.Have you consider offering one horovodjob demo in home page.
We will deprecate the horovodjob because it's not very user friendly, and no plans to deliver document.

> 2. The init container of mpijob git-sync ,does it provide the same functionality of the init container of horovodjob rsync
You can open an issue against it. But it's not high priority for us.
