### ISSUE TITLE
 error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope"

### ISSUE THREAD

**Issue by nowbug** [AliyunContainerService/arena#8]
阿里的大牛你好，我是一个新手，当我使用安装文档时  
 kubectl create -f arena/kubernetes-artifacts/tf-operator/tf-operator.yaml

遭遇了错误，以下是错误日志，我猜测可能是我环境有问题，不知道能否给出一些建议。
configmap/tf-job-operator-config created
serviceaccount/tf-job-operator created
clusterrole.rbac.authorization.k8s.io/tf-job-operator created
clusterrolebinding.rbac.authorization.k8s.io/tf-job-operator created
clusterrole.rbac.authorization.k8s.io/tf-job-dashboard created
clusterrolebinding.rbac.authorization.k8s.io/tf-job-dashboard created
serviceaccount/tf-job-dashboard created
deployment.extensions/tf-job-dashboard created
error: error validating "arena/kubernetes-artifacts/tf-operator/tf-operator.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): missing required field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by nowbug** [comment]
我是本地虚拟机搭建 centos7.3+kubernetes1.11

**Comment by cheyang** [comment]
Kubernetes 1.11对于CRD的校验比较苛刻，你可以先尝试一下1.10或者1.9的Kubernetes。我也会给tf-operator开issue，追踪一下这个问题。

**Comment by nowbug** [comment]
感谢，我会尝试使用1.10 or 1.9 再次尝试，这个项目真的很赞。

**Comment by cheyang** [comment]
谢谢，你可以直接在https://www.katacoda.com/courses/kubernetes/playground上测试。也欢迎您提issue和贡献代码。

```
master $ kubectl create -f arena/kubernetes-artifacts/tf-operator/tf-operator.yaml
configmap "tf-job-operator-config" created
serviceaccount "tf-job-operator" created
clusterrole.rbac.authorization.k8s.io "tf-job-operator" created
clusterrolebinding.rbac.authorization.k8s.io "tf-job-operator" created
clusterrole.rbac.authorization.k8s.io "tf-job-dashboard" created
clusterrolebinding.rbac.authorization.k8s.io "tf-job-dashboard" created
serviceaccount "tf-job-dashboard" created
deployment.extensions "tf-job-dashboard" created
customresourcedefinition.apiextensions.k8s.io "tfjobs.kubeflow.org" created
deployment.extensions "tf-job-operator-v1alpha2" created
service "tf-job-dashboard" created
```
